flags: {}
packages:
- '.'

resolver: nightly-2022-06-04
extra-deps: [template-haskell-compat-v0208-0.1.9]

allow-newer: false

nix:
  # Not using pure here because it is very practical to inherit
  # $NVIM_LISTEN_ADDRESS when developing and debugging plugins.
  pure: false

  packages:
  - zlib
  - neovim # for api generation
