flags: {}
packages:
- '.'
resolver: nightly-2020-02-04
extra-deps: []

allow-newer: false

nix:
  # Not using pure here because it is very practical to inherit
  # $NVIM_LISTEN_ADDRESS when developing and debugging plugins.
  pure: false

  packages:
  - zlib
  - neovim # for api generation
